<%@ Page Title="" Language="C#" MasterPageFile="~/Default.Master" AutoEventWireup="true" CodeBehind="Lessons.aspx.cs" Inherits="WebApplication9.Lessons" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
<table width="560" align="center">                  
                    <tr>
                       <td class="h1">Налични уроци:</td> 
                    </tr>        
                    
                    <tr>
                                                
                        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString2 %>"
                            SelectCommand="SELECT * FROM [Lesson]"
                            DeleteCommand="DELETE FROM [Lesson] WHERE [LessonID] = @LessonID">
                            <DeleteParameters>
                                <asp:Parameter Name="LessonID" Type="Int32" />
                            </DeleteParameters>
                        </asp:SqlDataSource>
                    </tr>  
                    
                    <tr>
                    <td>
                    <asp:LoginView ID="LoginView1" runat="server" EnableViewState="false">
                                <RoleGroups>
                                    <asp:RoleGroup Roles="admin">
                                        <ContentTemplate>
                                        <asp:GridView ID="GridView1" AllowSorting="True" AllowPaging="True" runat="server"
                                            DataSourceID="SqlDataSource1" DataKeyNames="LessonID"
                                            AutoGenerateColumns="False" Width="700px" AutoGenerateDeleteButton="False" >
                                            <Columns>
                                                <asp:HyperLinkField DataTextField="Title" HeaderText="Заглавие" SortExpression="Title" DataNavigateUrlFields="LessonId"  DataNavigateUrlFormatString="Read.aspx?lessonid={0}" />
                                                <asp:BoundField DataField="Url" HeaderText="Линк" SortExpression="Url" />
                                                <asp:CommandField ShowDeleteButton="True" DeleteText="Изтриване"/>
                                            </Columns>
                                          </asp:GridView> 
                                             <asp:LinkButton ID="LinkButton1" OnClick="LinkButton_Click" Text="Добави нов урок" runat="server"> </asp:LinkButton>
                                        </ContentTemplate>
                                    </asp:RoleGroup>
                                    <asp:RoleGroup Roles="member">
                                    <ContentTemplate>
                                     <asp:GridView ID="GridView2" AllowSorting="True" AllowPaging="True" runat="server"
                                            DataSourceID="SqlDataSource1" DataKeyNames="LessonID"
                                            AutoGenerateColumns="False" Width="700px">
                                            <Columns>
                                                <asp:HyperLinkField DataTextField="Title" HeaderText="Заглавие" SortExpression="Title" DataNavigateUrlFields="LessonId"  DataNavigateUrlFormatString="Read.aspx?lessonid={0}" />
                                            </Columns>
                                          </asp:GridView> 
                                          </ContentTemplate>
                                    </asp:RoleGroup>

                                </RoleGroups>
                            </asp:LoginView>
                    </td>
                    </tr>                                                                                          
                </table> 
</asp:Content>
